<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="appledeMacBook-Pro-72.local" name="Api_Select(failed)(failed)" tests="5" failures="2" timestamp="27 Aug 2018 09:37:12 GMT" time="0.741" errors="0">
  <testcase name="testMethod" time="0.053" classname="finup.feather.controller.HttpRequest_TestNG_New">
    <failure type="java.lang.AssertionError" message="/api/v1/crawler#####{&amp;quot;channelId&amp;quot;:&amp;quot;5000&amp;quot;,&amp;quot;delayCount&amp;quot;:0,&amp;quot;mkey&amp;quot;:&amp;quot;id_num_biz&amp;quot;,&amp;quot;mvalue&amp;quot;:&amp;quot;xyf00e31a0106460f951df9e99386cd78326e02c00f27fd0522cd645768e58e6de20160926&amp;quot;,&amp;quot;needDebugInfo&amp;quot;:true,&amp;quot;recieveTime&amp;quot;:1530854352476,&amp;quot;requestId&amp;quot;:&amp;quot;9af7e31b73634e82b08f6db87bcca280&amp;quot;,&amp;quot;requestTime&amp;quot;:0,&amp;quot;sync&amp;quot;:false,&amp;quot;tagName&amp;quot;:&amp;quot;TAOBAO_TRANS_DETAIL&amp;quot;} expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: /api/v1/crawler#####{"channelId":"5000","delayCount":0,"mkey":"id_num_biz","mvalue":"xyf00e31a0106460f951df9e99386cd78326e02c00f27fd0522cd645768e58e6de20160926","needDebugInfo":true,"recieveTime":1530854352476,"requestId":"9af7e31b73634e82b08f6db87bcca280","requestTime":0,"sync":false,"tagName":"TAOBAO_TRANS_DETAIL"} expected [true] but found [false]
	at finup.feather.controller.HttpRequest_TestNG_New.testMethod(HttpRequest_TestNG_New.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testMethod -->
  <testcase name="testMethod" time="0.063" classname="finup.feather.controller.HttpRequest_TestNG_New">
    <failure type="java.lang.AssertionError" message="/api/v1/oneTagName#####{&amp;quot;channelId&amp;quot;:&amp;quot;&amp;quot;,&amp;quot;param&amp;quot;:{&amp;quot;idCardNum&amp;quot;:&amp;quot;xyb76877f17d1588e080e4f2aa88d3c0361a40060626c877594a8fabe583b29bdf20160926&amp;quot;},&amp;quot;tagName&amp;quot;:&amp;quot;TBA014&amp;quot;} expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: /api/v1/oneTagName#####{"channelId":"","param":{"idCardNum":"xyb76877f17d1588e080e4f2aa88d3c0361a40060626c877594a8fabe583b29bdf20160926"},"tagName":"TBA014"} expected [true] but found [false]
	at finup.feather.controller.HttpRequest_TestNG_New.testMethod(HttpRequest_TestNG_New.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- testMethod -->
  <testcase name="testMethod" time="0.082" classname="finup.feather.controller.HttpRequest_TestNG_New"/>
  <testcase name="testMethod" time="0.086" classname="finup.feather.controller.HttpRequest_TestNG_New"/>
  <testcase name="testMethod" time="0.737" classname="finup.feather.controller.HttpRequest_TestNG_New"/>
</testsuite> <!-- Api_Select(failed)(failed) -->
